version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        command: pnpm dev
        environment:
            - NODE_ENV=development
